apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-there
spec:
  project: default
  source:
    path: helloworld_app
    repoURL: 'https://github.com/startfromit/docker_k8s.git'
    targetRevision: HEAD
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'