# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "192.168.0.104"  # 允许外部访问，不要使用0.0.0.0，helm会无法访问
  apiServerPort: 6443 # 固定端口
  serviceSubnet: 10.0.0.0/16
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
kubeadmConfigPatches:
- |-
  apiVersion: kubeadm.k8s.io/v1beta3
  kind: ClusterConfiguration
  metadata:
    name: config
  imageRepository: registry.aliyuncs.com/google_containers  # 替换为阿里云镜像仓库[1,3,5](@ref)
  nodeRegistration:
    kubeletExtraArgs:
      pod-infra-container-image: registry.aliyuncs.com/google_containers/pause:3.10  # 指定基础容器镜像[2,3](@ref)
